# Generated by Django 3.1.2 on 2020-10-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endgem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='dateAdded',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='material',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
